create database Ecommerce_analysis;
use Ecommerce_analysis;

select * from ecommerce_orders;
-- Total number of rows in the dataset
select count(*) as Total_rows
from ecommerce_orders;

-- All columns and the first 10 rows of the dataset.
select * from ecommerce_orders
limit 10;

-- The total number of orders in the dataset.
select count(OrderID) from ecommerce_orders;

-- Total number of unique customers.
select count(distinct CustomerID) 
from ecommerce_orders;

-- The number of unique products.
select count(distinct Product) 
from ecommerce_orders;

-- All unique payment methods
select distinct `Payment Method`
from ecommerce_orders;

-- All unique order statuses
select distinct `Order Status`
from ecommerce_orders;

-- All unique referral sources.
select distinct `Referral Source`
from ecommerce_orders;

-- All orders where the Product is Phone.
select * 
from ecommerce_orders
where Product = 'Phone';

-- All orders where the OrderStatus is Shipped
select * 
from ecommerce_orders
where `Order Status` = 'Shipped';

-- All orders where the Quantity is greater than 3.
select * from ecommerce_orders
where Quantity > 3;

-- All orders where the TotalPrice is greater than 1,000.
select * from ecommerce_orders
where `Total Price` > 1000;

-- All orders paid for using Credit Card.
select * from ecommerce_orders
where `Payment Method` = 'Credit Card'; 

-- All orders that came from Instagram.
select * from ecommerce_orders
where `Referral Source` = 'Instagram';

-- All orders where the order status is either Cancelled or Returned.
select * 
from ecommerce_orders
where `Order Status` IN ('Cancelled','Returned');

-- Total revenue for each product.
select  Product , round(sum(`Total Price`) ,2 ) as `Total revenue by Product`
from ecommerce_orders
group by Product;

-- Total number of orders for each product.
select  Product , count(OrderID) as `Total number of orders by Product`
from ecommerce_orders
group by Product;

-- Average order value for each product.
select  Product , round(avg(`Total Price`),2) as `Average order value`
from ecommerce_orders
group by Product;

-- Total revenue for each payment method.
select  `Payment method` , round(sum(`Total Price`) ,2 ) as `Total revenue by Payment Method`
from ecommerce_orders
group by `Payment Method`;

-- The number of orders for each payment method
select `Payment method`, count(OrderID) as `Total number of orders by Payment Method`
from ecommerce_orders
group by `Payment method`;

-- The total revenue for each order status.
select  `Order Status` , round(sum(`Total Price`) ,2 ) as `Total revenue by Order Status`
from ecommerce_orders
group by `Order Status`;

-- The number of orders for each order status.
select `Order Status`, count(OrderID) as `Total number of orders by Order Status`
from ecommerce_orders
group by `Order Status`;

-- The total revenue generated by each referral source
select `Referral Source`, count(`Referral Source`) as `Total number of orders by Referral Source`
from ecommerce_orders
group by `Referral Source`;

-- The number of orders from each referral source.
select `Referral Source`, count(OrderID) as `Total number of orders by Referral Source`
from ecommerce_orders
group by `Referral Source`;

-- The 10 orders with the highest TotalPrice.
select OrderID , round((`Total Price`), 2)
from ecommerce_orders
order by  `Total Price` DESC
limit 10;

-- The 10 orders with the lowest TotalPrice.
select OrderID , round((`Total Price`), 2)
from ecommerce_orders
order by  `Total Price` ASC
limit 10;

-- All orders sorted by Quantity from highest to lowest.
select OrderID , Quantity
from ecommerce_orders
order by  Quantity desc;

-- All orders sorted by Date, starting with the most recent order.
select OrderID , Date
from ecommerce_orders
order by Date desc;

-- The total revenue using TotalPrice.
Select round(sum(`Total Price`), 2) as Total_Revenue
from ecommerce_orders;

-- The average order value
select OrderID , avg(`Total Price`) as avg_order_value
from  ecommerce_orders
group by OrderID;

-- The highest order value.
select *
from  ecommerce_orders
Order by `Total Price` desc
limit 1;

-- The lowest order value.
select *
from  ecommerce_orders
Order by `Total Price` asc
limit 1;

-- The total quantity of products sold.
select sum(Quantity)
from ecommerce_orders;

-- The average quantity of items per order.
SELECT AVG(Quantity) AS average_quantity_per_order
FROM ecommerce_orders;

-- Which product generated the highest total revenue?
select Product , round(sum(`Total Price`), 2) as total_revenue
from ecommerce_orders
group by Product
order by total_revenue Desc
limit 1;

-- Which product had the highest number of orders?
select Product , count(OrderID) as Number_of_Orders
from ecommerce_orders
group by Product
order by Number_of_Orders Desc
limit 1;

-- Which payment method generated the most revenue?
select `Payment Method`, round(sum(`Total Price`), 2) as total_revenue
from ecommerce_orders
group by `Payment Method`
order by total_revenue Desc
limit 1;

-- Which referral source generated the most revenue?
select `Referral Source`, round(sum(`Total Price`), 2) as total_revenue
from ecommerce_orders
group by `Referral Source`
order by total_revenue Desc
limit 1;

-- What percentage of orders were shipped?
select (count(case WHEN `Order Status`= 'Shipped' then 1 end) *100) / count(*) as shipped_Pecentage
from ecommerce_orders;

-- What percentage of orders were cancelled?
select (count(case WHEN `Order Status`= 'Cancelled' then 1 end) *100) / count(*) as Cancelled_Pecentage
from ecommerce_orders;

-- Which product has the highest average order value?
select Product , round(avg(`Total Price`) ,2) as avg_order_value
from ecommerce_orders
group by Product
order by avg_order_value
limit 1;

-- Which order status has the highest total revenue?
select `Order Status` , round(sum(`Total Price`) ,2) as Total_revenue
from ecommerce_orders
group by `Order Status`
order by Total_revenue desc
limit 1;
-- Find the top 3 products by total revenue.
select Product , round(sum(`Total Price`) ,2) as Total_revenue
from ecommerce_orders
group by Product
order by Total_revenue desc
limit 3;

-- Find the top 5 customers by total spending.
select CustomerID, round(sum(`Total Price`) ,2) as Total_revenue
from ecommerce_orders
group by CustomerID
Order by Total_revenue desc
limit 5;

-- Find the top 5 orders with the highest quantity.
select *
from ecommerce_orders
Order by Quantity desc
limit 5;

-- Find the total revenue generated by each product and sort it from highest to lowest.
select Product ,round(sum(`Total Price`)) as Total_revenue
from ecommerce_orders
group by Product
order by Total_revenue desc;

-- Find the number of orders and total revenue for each product in one query.
select  Product, count(OrderID) as Number_of_Orders , round(sum(`Total Price`))  Total_revenue
from ecommerce_orders
group by Product;

-- Find the average TotalPrice for each OrderStatus.
select `Order Status` , round(avg(`Total Price`), 2) as AVG_Total_Price
from ecommerce_orders
group by `Order Status`;
-- Find the referral source with the highest number of orders.
select `Referral Source` , count(OrderID) as Total_Orders
from ecommerce_orders
group by `Referral Source` 
order by Total_Orders Desc
limit 1;
-- Find customers who have placed more than one order.
select CustomerID , count(OrderID) as Total_Orders
from ecommerce_orders
group by CustomerID
having Total_Orders > 1;